### ISSUE TITLE
Is github not suported?

### ISSUE THREAD

**Issue by hcpss-banderson** [xuwupeng2000/capistrano-scm-gitcopy#16]
I am getting empty tarballs and running deployments that complete, but are empty. I believe that no code is being pulled from my GitHub repo, but the script continues the deployment anyway. I have tried different configurations for the :repo_url like:

```ruby
set :repo_url, 'git@github.com:me/my-repo.git'
```

With this config I get:

```
Invalid command: 'git-upload-archive 'me/myrep.git''
  You appear to be using ssh to clone a git:// URL.
  Make sure your core.gitProxy config option and the
  GIT_PROXY_COMMAND environment variable are NOT set.
fatal: The remote end hung up unexpectedly
```

I have also tried:

```ruby
set :repo_url, 'https://me:my-password@github.com/me/my-repo.git'
```

But then I get this error:

```
fatal: Operation not supported by protocol.
```

[It looks like GitHub does not support archiving](https://help.github.com/articles/can-i-archive-a-repository/). I guess I am just asking for clarification that this strategy will not work with GitHub?

**Comment by carld** [comment]
Hey there,

Just checking what version of git you're on?

Recall a similar error with a ~1.5 version

Thanks,
Carl

**Comment by hcpss-banderson** [comment]
1.9.1

**Comment by hcpss-banderson** [comment]
This is starting from line 4 of /lib/capistrano/tasks/gitcopy.rake:

```ruby
  desc "Archive files to #{archive_name}"
  file archive_name do |file|
    no_repo_url = fetch(:repo_url) !~ /\S/

    if no_repo_url
      system "git ls-tree #{fetch(:branch)} > /dev/null"
    else
      system "git ls-remote #{fetch(:repo_url)} | grep #{fetch(:branch)}"
    end

    if $?.exitstatus == 0
      system "git archive #{no_repo_url ? '' : "--remote #{fetch(:repo_url)}" } --format=tar #{fetch(:branch)}:#{fetch(:sub_directory)} | gzip > #{ archive_name }"
    else
      puts "Can't find commit for: #{fetch(:branch)}"
    end
  end
```

It looks to me like this is the line that gets the archive:

```ruby
 system "git archive #{no_repo_url ? '' : "--remote #{fetch(:repo_url)}" } --format=tar #{fetch(:branch)}:#{fetch(:sub_directory)} | gzip > #{ archive_name }"
```

And since github does not support `archive` it won't work with a github repo.

**Comment by Daniel-ltw** [comment]
git archive is a command that retrieves a tree from a repository and archive it. 

With the --remote option, it picks it off from the remote repository that you specify. 

One thing that we notice previously is how git archive has issues in retrieving that remote repository branch. If the branch is your basic develop and master, it seem to work like a charm, but when you start calling for a complex branch that is not on your local box, it would definitely fail. 

github does not support archive only means that they do not archive your repository for you. That is my understanding when reading https://help.github.com/articles/can-i-archive-a-repository/

**Comment by hcpss-banderson** [comment]
If that were the case wouldn't their workaround be running "git archive"? Instead they recommend cloning the repo.

I am new to git, but shouldn't this command give me an archive of Drupal:

```
git archive --remote=git@github.com:drupal/drupal.git --format=tar HEAD | gzip > archive.tar.gz
```

I get:

```
Invalid command: 'git-upload-archive 'drupal/drupal.git''
```

The same command works when "remote" is my own private git server.

**Comment by hcpss-banderson** [comment]
I have contacted github support to clarify.

**Comment by hcpss-banderson** [comment]
Here is the response from Github support:
> We don't support using git-archive to pull an archive directly from GitHub. You can either clone the repo locally and run git-archive, or click on the Download ZIP button on the repo page.

**Comment by dchersey** [comment]
+1 on this.. trying to deploy to a  customer server that does not have internet access. Script worked really well until I found out they can't access bitbucket, only github. Github does not support archive. 

Workaround: 

Clone the repo to the customer deploy machine (which has access to github)

change deploy.rb to include
```ruby
set :repo_url, '.'
```
And that's it. 
Deploy procedure is now:
```bash
git pull
bundle exec cap <target> deploy
```

**Comment by craigcarnell** [comment]
@dchersey  @hcpss-banderson @Daniel-ltw Trying to use this for the first time, getting this:

```
** Execute deploy:updating
** Invoke gitcopy:create_release (first_time)
** Invoke gitcopy:deploy (first_time)
** Invoke archive.20150727071437993767.tar.gz (first_time)
** Execute archive.20150727071437993767.tar.gz
2e822d18754175a3c22a401dc15648754582ebee	refs/heads/master
Invalid command: 'git-upload-archive 'xxx/helpline.git''
  You appear to be using ssh to clone a git:// URL.
  Make sure your core.gitProxy config option and the
  GIT_PROXY_COMMAND environment variable are NOT set.
fatal: The remote end hung up unexpectedly
2e822d18754175a3c22a401dc15648754582ebee	refs/heads/master
Invalid command: 'git-upload-archive 'xxx/helpline.git''
  You appear to be using ssh to clone a git:// URL.
  Make sure your core.gitProxy config option and the
  GIT_PROXY_COMMAND environment variable are NOT set.
fatal: The remote end hung up unexpectedly
** Execute gitcopy:deploy
```

Is this the same issue?

**Comment by Saicheg** [comment]
faced with exact same error, setting `repo_url` to `.` solved problem for me!

**Comment by hcpss-banderson** [comment]
@xuwupeng2000, does closing this mean that github is not supported?

**Comment by xuwupeng2000** [comment]
Hi 

Honestly I only tested it with github. So I am sure it works with github.
You can open a new issue and let us know what is the issue, some details.

Thank you
