### ISSUE TITLE
Delete archives also on deploy failed

### ISSUE THREAD

**Issue by shtirlic** [xuwupeng2000/capistrano-scm-gitcopy#21]
Is there any chance to handle capistrano fail and cleanup archives after?

**Comment by jackwu-figured** [comment]
Yes can be done by catch exception man.
I may do this feature later. 
Currently busy with job hunting...

**Comment by carld** [comment]
Hey Jack, how's it going? long time!

**Comment by xuwupeng2000** [comment]
Hi Carl I am good.
Long time no see you. :smiley:
