### ISSUE TITLE
Brand new release -Test please

### ISSUE THREAD

**Issue by xuwupeng2000** [xuwupeng2000/capistrano-scm-gitcopy#36]
I just released version 0.1.2 (master branch)
Can someone plz confirm it is working ? 

Thanks

**Comment by vraravam** [comment]
Not working :(

INFO [81032614] Running /usr/bin/env mkdir -p /tmp/my_prog/ as shims@localhost
INFO [81032614] Finished in 0.007 seconds with exit status 0 (successful).
INFO [77280bf3] Running /usr/bin/env chmod +x /tmp/my_prog/git-ssh.sh as shims@localhost
INFO [77280bf3] Finished in 0.007 seconds with exit status 0 (successful).
INFO [16fab3f3] Running /usr/bin/env mkdir -p /tmp/my_prog/ as shims@localhost
INFO [16fab3f3] Finished in 0.006 seconds with exit status 0 (successful).
INFO [c4386a19] Running /usr/bin/env chmod +x /tmp/my_prog/git-ssh.sh as shims@localhost
INFO [c4386a19] Finished in 0.007 seconds with exit status 0 (successful).
INFO [359d0a79] Running /usr/bin/env git ls-remote --heads config/../../my_prog.git as shims@localhost
INFO [359d0a79] Finished in 0.013 seconds with exit status 0 (successful).
INFO [1e908e68] Running /usr/bin/env git ls-remote --heads config/../../my_prog.git as shims@localhost
INFO [1e908e68] Finished in 0.015 seconds with exit status 0 (successful).
INFO [73130cd4] Running /usr/bin/env mkdir -p /var/www/my_prog/shared /var/www/my_prog/releases as ubuntu@1.2.3.4
INFO [73130cd4] Finished in 0.081 seconds with exit status 0 (successful).
INFO [ee8f474f] Running /usr/bin/env mkdir -p /var/www/my_prog/shared/log /var/www/my_prog/shared/tmp /var/www/my_prog/shared/public/assets /var/www/my_prog/shared/public/assets as ubuntu@1.2.3.4
INFO [ee8f474f] Finished in 0.087 seconds with exit status 0 (successful).
INFO [4b5111a0] Running /usr/bin/env mkdir -p /var/www/my_prog/shared/config /var/www/my_prog/shared/config as ubuntu@1.2.3.4
INFO [4b5111a0] Finished in 0.081 seconds with exit status 0 (successful).
INFO [1fb43d7d] Running /usr/bin/env mkdir -p /tmp/my_prog-repository as shims@localhost
INFO [1fb43d7d] Finished in 0.010 seconds with exit status 0 (successful).
INFO [c4a46aaf] Running /usr/bin/env git clone --verbose --mirror config/../../my_prog.git /tmp/my_prog-repository as shims@localhost
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Command::Failed: git exit status: 32768
git stdout: Nothing written
git stderr: fatal: repository 'config/../../my_prog.git' does not exist

Tasks: TOP => gitcopy:create_release => gitcopy:create_tarfile => gitcopy:update => gitcopy:clone
(See full trace by running task with --trace)
The deploy has failed with an error: git exit status: 32768
git stdout: Nothing written
git stderr: fatal: repository 'config/../../my_prog.git' does not exist
