### ISSUE TITLE
Installation not work / LoadError: cannot load such file -- capistrano/gitcopy.rb

### ISSUE THREAD

**Issue by Bubelbub** [xuwupeng2000/capistrano-scm-gitcopy#37]
Hey guys,

I get this error.

    LoadError: cannot load such file -- capistrano/gitcopy.rb

If I follow the installation process.

I added `gem 'capistrano-scm-gitcopy'` in the `GemFile` and replaced the :scm string with `set :scm, :gitcopy`.
But then I get this error.

If I add this bad `` to the `Capfile` it seems to work but then I get this error. I think this is because I'm using windows?

	** Execute gitcopy:wrapper
	INFO [2f6bed48] Running /usr/bin/env mkdir -p /tmp/app/ as Username@localhost
	DEBUG [2f6bed48] Command: ( export SYMFONY_ENV="prod" ; /usr/bin/env mkdir -p /tmp/app/ )
	cap aborted!
	Errno::ENOENT: No such file or directory - ( export SYMFONY_ENV="prod" ; /usr/bin/env mkdir -p /tmp/app/ )
	C:/Ruby22-x64/lib/ruby/2.2.0/open3.rb:193:in `spawn'
	C:/Ruby22-x64/lib/ruby/2.2.0/open3.rb:193:in `popen_run'
	C:/Ruby22-x64/lib/ruby/2.2.0/open3.rb:93:in `popen3'
	C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sshkit-1.9.0/lib/sshkit/backends/local.rb:41:in `execute_command'
	C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:137:in `block in create_command_and_execute'

Thanks in Advance for any ideas!

**Comment by Bubelbub** [comment]
Also via copy it's not working for now, @xuwupeng2000.
But in the meanwhile I created a private repository on Bitbucket and I'm working with that.

**Comment by xuwupeng2000** [comment]
Hi 

You can reopen it again.
I does not throw this error to me on both Mac and Linux.
You can open a new issue and give me some details

Thank you

**Comment by xuwupeng2000** [comment]
Finally, DO NOT ADD require 'capistrano/gitcopy' to Capfile because capistrano/setup already loads the scm module with the :scm value you specified.



Does that solve your issue BTW ?

Thanks
