### ISSUE TITLE
Directory already exist and is not empty

### ISSUE THREAD

**Issue by ofostier** [xuwupeng2000/capistrano-scm-gitcopy#40]
Hi
I'm using capistrano 3.5 with Ubuntu 16 

Deploy fail with error 

```
DEBUG [7684efec] 	Cloning into bare repository '/tmp/capipro-repository/1463328717'...
DEBUG [7684efec] 	POST git-upload-pack (gzip 33402 to 16590 bytes)

INFO [7684efec] Finished in 102.995 seconds with exit status 0 (successful).
INFO [c40c4941] Running /usr/bin/env mkdir -p /tmp/capipro-repository/1463328717 as ftpdata@localhost
DEBUG [c40c4941] Command: /usr/bin/env mkdir -p /tmp/capipro-repository/1463328717
INFO [c40c4941] Finished in 0.004 seconds with exit status 0 (successful).
DEBUG [6530b4ab] Running if test ! -d /tmp/capipro-repository/1463328717; then echo "Directory does not exist '/tmp/capipro-repository/1463328717'" 1>&2; false; fi as ftpdata@localhost
DEBUG [6530b4ab] Command: if test ! -d /tmp/capipro-repository/1463328717; then echo "Directory does not exist '/tmp/capipro-repository/1463328717'" 1>&2; false; fi
DEBUG [6530b4ab] Finished in 0.006 seconds with exit status 0 (successful).
INFO [4bf89768] Running /usr/bin/env git clone --verbose --mirror http://pass:user@bitbucket.xxx.fr/scm/cfw/test.git /tmp/capipro-repository/1463328717 as ftpdata@localhost
DEBUG [4bf89768] Command: cd /tmp/capipro-repository/1463328717 && ( export GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/capipro/git-ssh.sh" ; /usr/bin/env git clone --verbose --mirror http://pass:user@bitbucket.xxx.fr/scm/cfw/test.git /tmp/capipro-repository/1463328717 )
DEBUG [4bf89768] 	fatal: destination path '/tmp/capipro-repository/1463328717' already exists and is not an empty directory.
cap aborted!
SSHKit::Command::Failed: git exit status: 32768
git stdout: Nothing written
git stderr: fatal: destination path '/tmp/capipro-repository/1463328717' already exists and is not an empty directory.

```

I'm using just a basic deployement configuration in deploy.rb

```
# config valid only for current version of Capistrano
lock '3.5.0'

set :application, 'capipro'
set :repo_url, 'http://pass:user@bitbucket.xxx.fr/scm/cfw/test.git'

# Default branch is :master
 ask :branch, `git rev-parse --abbrev-ref HEAD`.chomp

# Default value for :scm is :git .... :gitcopy
set :scm, :gitcopy

```

and stagin.rb

```
# server-based syntax
# ======================
# Defines a single server with a list of roles and multiple properties.
# You can define all roles on a single server, or split them:

server '172.17.0.3', user: 'ftpdata', roles: %w{a`pp}

role :app, %w{ftpdata@172.17.0.3}

```

Any idea ?

Olivier

**Comment by xuwupeng2000** [comment]
git stderr: fatal: destination path '/tmp/capipro-repository/1463328717' already exists and is not an empty directory.

Delete this exiting folder and deploy again ?! I think that may solve the problem.

**Comment by ofostier** [comment]
I already delete all tmp files few time before start a deploy.
But, has you can see, gitcopy create the same directory 2 times.
At the first time the directory doesn't exist so he can create it.

**Comment by joerixaop** [comment]
Did you require "capistrano/gitcopy" in your Capfile?

**Comment by hoeni** [comment]
Same here.

The whole thing is performed twice:

    INFO [c75fc778] Running /usr/bin/env mkdir -p /tmp/couscous-repository/1467384324 as vagrant@localhost
    INFO [c75fc778] Finished in 0.004 seconds with exit status 0 (successful).
    INFO [e3f4b21d] Running /usr/bin/env git clone --verbose --mirror ssh://XXX/mitxp-csc /tmp/couscous-repository/1467384324 as vagrant@localhost
    INFO [e3f4b21d] Finished in 1.285 seconds with exit status 0 (successful).
    INFO [88d9cc5b] Running /usr/bin/env mkdir -p /tmp/couscous-repository/1467384324 as vagrant@localhost
    INFO [88d9cc5b] Finished in 0.002 seconds with exit status 0 (successful).
    INFO [312b45f1] Running /usr/bin/env git clone --verbose --mirror ssh://XXX/mitxp-csc /tmp/couscous-repository/1467384324 as vagrant@localhost

The error occures while cloning the second time...

**Comment by joerixaop** [comment]
Same question.

The point is that you shouldn't require it in your Capfile (I should have perhaps mentioned that in my first post), because that gives you this error.

At least for me removing the require from the Capfile solved that issue.

**Comment by hoeni** [comment]
Well that was indeed with the require in the capfile. When I don;t have the require i get

    LoadError: cannot load such file -- capistrano/gitcopy.rb

**Comment by joerixaop** [comment]
What is the version of git-scm-copy according to bundler?

**Comment by joerixaop** [comment]
Does this (prefixing capistrano command with `bundle exec`) help?  https://github.com/wercker/capistrano-scm-copy/issues/17#issuecomment-142323868

**Comment by xuwupeng2000** [comment]
Don't include gitcopy.rb in Capfile.

**Comment by skonsoft** [comment]
I got the same error.

 when i remove from capfile the 
`require 'capistrano/gitcopy'`

i get:
`LoadError: cannot load such file -- capistrano/gitcopy.rb`

**and i dont use bundle...**

Is there any solution for this ?

regards !
