### ISSUE TITLE
cd /tmp/... is missing when running gitcopy:set_current_revision

### ISSUE THREAD

**Issue by ivan-kovalyov** [xuwupeng2000/capistrano-scm-gitcopy#42]
when i'm running cap x deploy from a folder that is not a git repo, it fails on  gitcopy:set_current_revision task. the log is below

INFO [f5f06bee] Running /usr/bin/env git remote update as user@localhost
DEBUG [f5f06bee] Command: cd /tmp/project-repository/1464541485 && ( export GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/project/git-ssh.sh" ; /usr/bin/env git remote update )
DEBUG [f5f06bee] 	Fetching origin
INFO [f5f06bee] Finished in 0.312 seconds with exit status 0 (successful).
DEBUG [e8eb8b2d] Running /usr/bin/env git rev-list --max-count=1 --abbrev-commit --abbrev=12 master as user@localhost
DEBUG [e8eb8b2d] Command: ( export GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/project/git-ssh.sh" ; /usr/bin/env git rev-list --max-count=1 --abbrev-commit --abbrev=12 master )
DEBUG [e8eb8b2d] 	fatal: Not a git repository (or any parent up to mount point /usr)
DEBUG [e8eb8b2d] 	Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

It looks like the reason is "cd /tmp/project-repository/1464541485 &&" needs to happen before running git rev-list

**Comment by xuwupeng2000** [comment]
Well gitcopy can only deploy a folder which is a git repo.
You can modify the code to skip those steps for git.
