### ISSUE TITLE
git doesn't find a repository to clone in /tmp

### ISSUE THREAD

**Issue by agnyp** [xuwupeng2000/capistrano-scm-gitcopy#44]
I have git version 1.9.1, updated to capistrano 3.5 and am getting the following error:

```
02 git clone --verbose --mirror  /tmp/stage-repository/1467722316
02 fatal: repository '/tmp/stage-repository/1467722316' does not exist
```

Any idea what went wrong?

**Comment by xuwupeng2000** [comment]
Do you have /tmp folder ?
Try the latest version plz.

**Comment by agnyp** [comment]
The /tmp/../.. folder is being created correctly.
I only have this problem with version 0.1.4. With 0.0.7 everything works fine.

**Comment by xuwupeng2000** [comment]
😭  0.1.4 is broken ....

**Comment by xuwupeng2000** [comment]
I have tested 0.1.4 it works fine.

**Comment by xuwupeng2000** [comment]
You can set local_path var in deploy.rb
