### ISSUE TITLE
LoadError: cannot load such file -- capistrano/gitcopy.rb

### ISSUE THREAD

**Issue by bennyzr** [xuwupeng2000/capistrano-scm-gitcopy#45]
Hi,

This still seems to be a problem.

Using Capistrano 3.6.1

All I did was:
1) add "gem 'capistrano-scm-gitcopy', group: :development" to my gemfile
2) add "set :scm, :gitcopy" to my deploy file.

**Comment by xuwupeng2000** [comment]
```
bundle exec cap staging deploy branch=master
```
You have to do bundle exec cap not just cap

**Comment by bennyzr** [comment]
Thanks.
I tried that and am now getting "fatal: No remote configured to list refs from."

**Comment by xuwupeng2000** [comment]
Cool.
Yup that is something else but not a issue with this gem.

http://stackoverflow.com/questions/20410138/how-do-i-configure-remote-refs-for-git-capistrano-3-in-ror-deployment 

Just may be this ?

**Comment by bennyzr** [comment]
Setting this "set :repo_url, '.'" in deploy solved it.
