### ISSUE TITLE
tar verbosity when extracting on remote

### ISSUE THREAD

**Issue by miks** [xuwupeng2000/capistrano-scm-gitcopy#47]
Is it really needed? For large project there are hundred of files.
I'm thinking about switch to configure this behaviour, but can we make assumption that default behaviour is without tar verbosity?

**Comment by miks** [comment]
Seems that is quite simple to just force Capistrano to be less verbose with:
```
set :format, :pretty
set :log_level, :info
```

**Comment by xuwupeng2000** [comment]
👍
